# Generated by Django 5.2 on 2025-05-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Product Option', 'verbose_name_plural': 'Product Options'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='Product'),
        ),
    ]
