# Generated by Django 5.2 on 2025-05-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_prices', to='products.product', verbose_name='Product'),
        ),
    ]
